#!/bin/bash
d_script="$(dirname $0)"
d_output="$(realpath "$d_script/.out")"
d_cmake="$(realpath "$d_script/.mid")"
d_build="$d_cmake"
# d_graph="$d_cmake/graph"

function clean() {
  echo ">> cleaning >>"
  rm -rf "$d_output"
  rm -rf "$d_build"
  # rm -rf "$d_graph"
  echo "<<"
}

profiles=("base" "h264" "h265")
backends=("wasm" "asm")

function __validate_args() {
  local IFS="|"
  local pval=$1
  local preg="\<${1}\>"
  if [[ ! ${profiles[@]} =~ $preg ]]; then
    echo "invalid codec profile: $pval. available: ${profiles[*]}"
    return 1;
  fi
  local bval=$2
  local breg="\<${2}\>"
  if [[ ! ${backends[@]} =~ $breg ]]; then
    echo "invalid codec backend: $bval. available: ${backends[*]}"
    return 1;
  fi
  return 0;
}

function __build_variant() {
  if !(__validate_args "${@}"); then
    return 1;
  fi
  local pval=$1
  local bval=$2
  emcmake cmake .. -DCODEC_PROFILE="$pval" -DCODEC_BACKEND="$bval"
  emmake make -j 4
  mv "../.output/bin/player-codec.js" "../.output/bin/$pval.$bval.js"
}

# function __graph_variant() {
#   if !(__validate_args "${@}"); then
#     return 1;
#   fi
#   local pval=$1
#   local bval=$2
#   local name=$1.$2.dot
#   emcmake cmake .. -DCODEC_PROFILE="$pval" -DCODEC_BACKEND="$bval" --graphviz="$name"
#   dot -Tpng -O "$name"
# }

function __meta_call() {
  local t_call=$1
  local d_call=$2
  local f_call=$3
  echo ">> $t_call >>"
  rm -rf "$d_call"
  rm -rf "$d_output"
  mkdir "$d_call"
  cd "$d_call"
  if [ $# -eq 3 ]; then
    for pval in "${profiles[@]}"; do
      for bval in "${backends[@]}"; do
        eval "$f_call" "$pval" "$bval"
      done
    done
  elif [ $# -eq 5 ]; then
    local pval=$4
    local bval=$5
    eval "$f_call" "$pval" "$bval"
  else
    help
    return 1
  fi
  echo "<<"
}

function help() {
printf "this is help\n"
}

case $1 in
  build) { __meta_call "building" "$d_build" "__build_variant" "${@:2}"; };;
  # graph) { __meta_call "graphing" "$d_graph" "__graph_variant" "${@:2}"; };;
  clean) { clean; };;
  *)     { help;	};;
esac